/* España · the Çelik plan: field-guide skeleton, generated from the mined
   dataset (29 vlogs, 22 blog articles). Ids, groups, counts and links only;
   every user-facing word lives in i18n.js under guide.*.
   m = how many vlogs mentioned the place (0 = blog pick). act = the
   itinerary stop it appears as. q = Google Maps search query. yt = a vlog
   moment showing it. blogs/src = indices into GUIDE.blogs. */
window.GUIDE = {
  groups: ['bcn', 'aroundbcn', 'vlc', 'aroundvlc', 'mad', 'sev'],
  cats: ['tickets', 'transport', 'food', 'timing', 'safety', 'budget', 'stay', 'daytrip', 'etiquette', 'misc'],
  places: [
    {"id":"sagrada","group":"bcn","name":"Sagrada Família","m":9,"act":"d2b1","q":"Sagrada Família, Barcelona","yt":"https://youtube.com/watch?v=uK_ghSTfn6U&t=952","blogs":[0]},
    {"id":"guell","group":"bcn","name":"Parc Güell","m":7,"act":"d2b3","q":"Parc Güell, Barcelona","yt":"https://youtube.com/watch?v=uK_ghSTfn6U&t=1081","blogs":[1]},
    {"id":"batllo","group":"bcn","name":"Casa Batlló","m":6,"act":"d2b4","q":"Casa Batlló, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=390","blogs":[0]},
    {"id":"bcncathedral","group":"bcn","name":"Catedral de la Santa Creu i Santa Eulàlia","m":4,"q":"Catedral de la Santa Creu i Santa Eulàlia, Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=292","blogs":[0]},
    {"id":"gothic","group":"bcn","name":"Gothic Quarter (Barri Gòtic)","m":4,"act":"d1b3","q":"Gothic Quarter (Barri Gòtic), Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=270","blogs":[1]},
    {"id":"rambla","group":"bcn","name":"La Rambla","m":4,"act":"d4b4","q":"La Rambla, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=330"},
    {"id":"palau","group":"bcn","name":"Palau de la Música Catalana","m":4,"q":"Palau de la Música Catalana, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=1440","blogs":[0]},
    {"id":"barceloneta","group":"bcn","name":"Barceloneta","m":3,"act":"d3b3","q":"Barceloneta, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=1500","blogs":[3]},
    {"id":"pedrera","group":"bcn","name":"Casa Milà (La Pedrera)","m":3,"act":"d2b2","q":"Casa Milà (La Pedrera), Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=187","blogs":[0]},
    {"id":"montjuic","group":"bcn","name":"Montjuïc","m":3,"q":"Montjuïc, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=930","blogs":[1]},
    {"id":"picasso","group":"bcn","name":"Museu Picasso","m":3,"act":"d4b3","q":"Museu Picasso, Barcelona","yt":"https://youtube.com/watch?v=uK_ghSTfn6U&t=633","blogs":[0]},
    {"id":"ciutadella","group":"bcn","name":"Parc de la Ciutadella","m":3,"q":"Parc de la Ciutadella, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=1230","blogs":[0]},
    {"id":"born","group":"bcn","name":"El Born (La Ribera)","m":2,"act":"d4b2","q":"la Ribera, Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=448","blogs":[2]},
    {"id":"placareial","group":"bcn","name":"Plaça Reial","m":2,"act":"d1b3","q":"Plaça Reial, Barcelona","yt":"https://youtube.com/watch?v=uK_ghSTfn6U&t=911"},
    {"id":"bisbe","group":"bcn","name":"Pont del Bisbe","m":2,"q":"Pont del Bisbe, Barcelona","yt":"https://youtube.com/watch?v=9tyzP8YDjDw&t=450"},
    {"id":"setportes","group":"bcn","name":"7 Portes","m":1,"q":"7 Portes, Barcelona"},
    {"id":"arc","group":"bcn","name":"Arc de Triomf","m":1,"q":"Arc de Triomf, Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=659","blogs":[0]},
    {"id":"arcano","group":"bcn","name":"Arcano","m":1,"q":"Arcano Restaurant Barcelona, Barcelona","yt":"https://youtube.com/watch?v=cKWUZLXbJKk&t=930"},
    {"id":"delmar","group":"bcn","name":"Basílica de Santa Maria del Mar","m":1,"act":"d4b2","q":"Basílica de Santa Maria del Mar, Barcelona","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=150","blogs":[0]},
    {"id":"bunkers","group":"bcn","name":"Bunkers del Carmel","m":1,"q":"Bunkers del Carmel, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=630","blogs":[2]},
    {"id":"calboter","group":"bcn","name":"Cal Boter","m":1,"q":"Restaurant Cal Boter, Barcelona"},
    {"id":"calpep","group":"bcn","name":"Cal Pep","m":1,"q":"Cal Pep, Barcelona","yt":"https://youtube.com/watch?v=9tyzP8YDjDw&t=840"},
    {"id":"campnou","group":"bcn","name":"Camp Nou","m":1,"q":"Camp Nou, Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=590"},
    {"id":"culleretes","group":"bcn","name":"Can Culleretes","m":1,"q":"Can Culleretes, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=1530","blogs":[0]},
    {"id":"cansole","group":"bcn","name":"Can Solé","m":1,"act":"d3b4","q":"Restaurant Can Solé, Barcelona","blogs":[0]},
    {"id":"merce","group":"bcn","name":"Carrer de la Mercè","m":1,"act":"d1b4","q":"Carrer de la Mercè, Barcelona"},
    {"id":"vicens","group":"bcn","name":"Casa Vicens","m":1,"q":"Casa Vicens, Barcelona","yt":"https://youtube.com/watch?v=cKWUZLXbJKk&t=180","blogs":[0]},
    {"id":"corgicafe","group":"bcn","name":"Corgi Café","m":1,"q":"Corgi cafe, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=570"},
    {"id":"raval","group":"bcn","name":"el Raval","m":1,"q":"el Raval, Barcelona","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=150"},
    {"id":"estadi","group":"bcn","name":"Estadi Olímpic Lluís Companys","m":1,"q":"Estadi Olímpic Lluís Companys, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=930"},
    {"id":"gracia","group":"bcn","name":"Gràcia","m":1,"q":"Gràcia, Barcelona","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=240","blogs":[2]},
    {"id":"santpau","group":"bcn","name":"Hospital de la Santa Creu i Sant Pau","m":1,"q":"Hospital de la Santa Creu i Sant Pau, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=690"},
    {"id":"hotelcolon","group":"bcn","name":"Hotel Colón rooftop","m":1,"q":"Hotel Colon, Barcelona","yt":"https://youtube.com/watch?v=cKWUZLXbJKk&t=390"},
    {"id":"colmena","group":"bcn","name":"La Colmena","m":1,"q":"Pastisseria La Colmena, Barcelona"},
    {"id":"manolobakes","group":"bcn","name":"Manolo Bakes","m":1,"q":"Manolo Bakes, Barcelona","yt":"https://youtube.com/watch?v=sRTZVjgUwHg&t=1320"},
    {"id":"boqueria","group":"bcn","name":"Mercat de la Boqueria","m":1,"act":"d4b4","q":"Mercat de la Boqueria, Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=255","blogs":[1]},
    {"id":"santacaterina","group":"bcn","name":"Mercat de Santa Caterina","m":1,"act":"d4b1","q":"Mercat de Santa Caterina, Barcelona","blogs":[3]},
    {"id":"xocolata","group":"bcn","name":"Museu de la Xocolata","m":1,"q":"Museu de la Xocolata, Barcelona","yt":"https://youtube.com/watch?v=cKWUZLXbJKk&t=690"},
    {"id":"passeig","group":"bcn","name":"Passeig de Gràcia","m":1,"q":"Passeig de Gràcia, Barcelona","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=210","blogs":[0]},
    {"id":"petra","group":"bcn","name":"Petra","m":1,"q":"Petra, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=780"},
    {"id":"espanya","group":"bcn","name":"Plaça d’Espanya","m":1,"q":"Plaça d’Espanya, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=870"},
    {"id":"catalunya","group":"bcn","name":"Plaça de Catalunya","m":1,"q":"Plaça de Catalunya, Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=617"},
    {"id":"felipneri","group":"bcn","name":"Plaça de Sant Felip Neri","m":1,"act":"d1b3","q":"Plaça de Sant Felip Neri, Barcelona","blogs":[0]},
    {"id":"portvell","group":"bcn","name":"Port Vell","m":1,"q":"Port Vell, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=1110"},
    {"id":"cordobes","group":"bcn","name":"Tablao Flamenco Cordobes","m":1,"q":"Tablao Flamenco Cordobes, Barcelona","yt":"https://youtube.com/watch?v=YILzH4iI76E&t=480"},
    {"id":"tibidabo","group":"bcn","name":"Tibidabo","m":1,"q":"Tibidabo, Barcelona","yt":"https://youtube.com/watch?v=juHOYfdXNQA&t=502","blogs":[2]},
    {"id":"timeout","group":"bcn","name":"Time Out Market","m":1,"q":"Time Out Market, Barcelona"},
    {"id":"ziryab","group":"bcn","name":"Ziryab Fusion Tapas Bar","m":1,"q":"Ziryab Fusion Tapas Bar, Barcelona","yt":"https://youtube.com/watch?v=cKWUZLXbJKk&t=450"},
    {"id":"barcalders","group":"bcn","name":"Bar Calders","m":0,"q":"Bar Calders, Barcelona","blogs":[4]},
    {"id":"pinotxo","group":"bcn","name":"Bar Pinotxo","m":0,"q":"Bar Pinotxo, La Boqueria, Barcelona","blogs":[4]},
    {"id":"canramonet","group":"bcn","name":"Can Ramonet","m":0,"q":"Can Ramonet, Barceloneta, Barcelona","blogs":[4]},
    {"id":"casaxica","group":"bcn","name":"Casa Xica","m":0,"q":"Casa Xica, Poble-sec, Barcelona","blogs":[4]},
    {"id":"calmarino","group":"bcn","name":"Celler Cal Marino","m":0,"q":"Celler Cal Marino, Barcelona","blogs":[4]},
    {"id":"els4gats","group":"bcn","name":"Els 4Gats","m":0,"q":"Els 4Gats, Barcelona","blogs":[1]},
    {"id":"sortidors","group":"bcn","name":"Els Sortidors del Parlament","m":0,"q":"Els Sortidors del Parlament, Barcelona","blogs":[4]},
    {"id":"magicfountain","group":"bcn","name":"Font Màgica de Montjuïc","m":0,"q":"Font Màgica de Montjuïc, Barcelona","blogs":[5]},
    {"id":"covafumada","group":"bcn","name":"La Cova Fumada","m":0,"q":"La Cova Fumada, Barceloneta, Barcelona","blogs":[4]},
    {"id":"lapubilla","group":"bcn","name":"La Pubilla","m":0,"q":"La Pubilla, Gràcia, Barcelona","blogs":[4]},
    {"id":"lasarenas","group":"bcn","name":"Las Arenas rooftop","m":0,"q":"Las Arenas, Plaça d’Espanya, Barcelona","blogs":[2]},
    {"id":"lostarantos","group":"bcn","name":"Los Tarantos","m":0,"q":"Los Tarantos, Plaça Reial, Barcelona","blogs":[1]},
    {"id":"ocata","group":"bcn","name":"Ocata & Castelldefels beaches","m":0,"q":"Platja d’Ocata, El Masnou","blogs":[5]},
    {"id":"palauguell","group":"bcn","name":"Palau Güell","m":0,"q":"Palau Güell, Barcelona","blogs":[1]},
    {"id":"piscines","group":"bcn","name":"Piscines Municipals de Montjuïc","m":0,"q":"Piscines Municipals de Montjuïc, Barcelona","blogs":[5]},
    {"id":"marbella","group":"bcn","name":"Platja de la Mar Bella","m":0,"q":"Platja de la Mar Bella, Barcelona","blogs":[3]},
    {"id":"bogatell","group":"bcn","name":"Platja del Bogatell","m":0,"q":"Platja del Bogatell, Barcelona","blogs":[3]},
    {"id":"poblesec","group":"bcn","name":"Poble-sec","m":0,"q":"Poble-sec, Barcelona","blogs":[0]},
    {"id":"poblenou","group":"bcn","name":"Poblenou","m":0,"q":"Poblenou, Barcelona","blogs":[3]},
    {"id":"quimet","group":"bcn","name":"Quimet & Quimet","m":0,"q":"Quimet & Quimet, Barcelona","blogs":[1]},
    {"id":"salamontjuic","group":"bcn","name":"Sala Montjuïc open-air cinema","m":0,"q":"Sala Montjuïc, Castell de Montjuïc, Barcelona","blogs":[5]},
    {"id":"santantoni","group":"bcn","name":"Sant Antoni","m":0,"q":"Mercat de Sant Antoni, Barcelona","blogs":[3]},
    {"id":"canmargarit","group":"bcn","name":"Taverna Can Margarit","m":0,"q":"Taverna Can Margarit, Barcelona","blogs":[4]},
    {"id":"montserrat","group":"aroundbcn","name":"Montserrat","m":4,"act":"d3b2","q":"Montserrat, Barcelona","yt":"https://youtube.com/watch?v=9tyzP8YDjDw&t=1080","blogs":[1,7,8]},
    {"id":"tossa","group":"aroundbcn","name":"Tossa de Mar","m":1,"q":"Tossa de Mar, Girona","yt":"https://youtube.com/watch?v=9tyzP8YDjDw&t=1050","blogs":[7]},
    {"id":"figueres","group":"aroundbcn","name":"Dalí Theatre-Museum, Figueres","m":0,"q":"Dalí Theatre-Museum, Figueres","blogs":[7]},
    {"id":"girona","group":"aroundbcn","name":"Girona","m":0,"q":"Girona old town","blogs":[1,7]},
    {"id":"sitges","group":"aroundbcn","name":"Sitges","m":0,"q":"Sitges, Barcelona","blogs":[7,0]},
    {"id":"tarragona","group":"aroundbcn","name":"Tarragona","m":0,"q":"Tarragona amphitheatre","blogs":[7]},
    {"id":"mercatcentral","group":"vlc","name":"Mercat Central","m":7,"act":"d5b1","q":"Mercat Central, València","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=510","blogs":[11]},
    {"id":"turia","group":"vlc","name":"Túria Gardens","m":5,"act":"d4b6","q":"Túria Gardens, València","yt":"https://youtube.com/watch?v=bXX-0J9V5vU&t=272","blogs":[11]},
    {"id":"vlccathedral","group":"vlc","name":"València Cathedral","m":5,"act":"d5b3","q":"València Cathedral, València","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=540","blogs":[12]},
    {"id":"virgen","group":"vlc","name":"Plaça de la Mare de Déu (Plaza de la Virgen)","m":3,"q":"Plaça de la Mare de Déu (Plaza de la Virgen), València","yt":"https://youtube.com/watch?v=dsaL__wExAQ&t=180","blogs":[12]},
    {"id":"malvarrosa","group":"vlc","name":"Platja de la Malva-rosa","m":3,"act":"d5b5","q":"Platja de la Malva-rosa, València","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=510","blogs":[11]},
    {"id":"carmenq","group":"vlc","name":"El Carmen","m":2,"act":"d5b7","q":"El Carmen, València","yt":"https://youtube.com/watch?v=bXX-0J9V5vU&t=77","blogs":[12]},
    {"id":"sannicolas","group":"vlc","name":"Església de Sant Nicolau","m":2,"q":"Cocatedral de Sant Nicolau de Bari, València","yt":"https://youtube.com/watch?v=aiohx6ug6vs&t=360","blogs":[11]},
    {"id":"hsantacatalina","group":"vlc","name":"Horchatería Santa Catalina","m":2,"q":"Horchateria de Santa Catalina, València","yt":"https://youtube.com/watch?v=dsaL__wExAQ&t=720","blogs":[12]},
    {"id":"ciencies","group":"vlc","name":"Museu de les Ciències","m":2,"act":"d6b1","q":"Museu de les Ciències, València","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=480"},
    {"id":"russafa","group":"vlc","name":"Ruzafa (Russafa)","m":2,"act":"d4b7","q":"Ruzafa (Russafa), València","yt":"https://youtube.com/watch?v=V792VL2-Qas&t=393","blogs":[11]},
    {"id":"serranos","group":"vlc","name":"Torres de Serranos","m":2,"act":"d5b6","q":"Torres dels Serrans, València","yt":"https://youtube.com/watch?v=aiohx6ug6vs&t=720","blogs":[12]},
    {"id":"bioparc","group":"vlc","name":"Bioparc València","m":1,"q":"Bioparc València, València","yt":"https://youtube.com/watch?v=LkpItPttOyM&t=1385"},
    {"id":"cafeinfanta","group":"vlc","name":"Café Infanta","m":1,"q":"Café Infanta, Plaza del Tossal, València"},
    {"id":"casacarmela","group":"vlc","name":"Casa Carmela","m":1,"q":"Casa Carmela, València","blogs":[14]},
    {"id":"centralbar","group":"vlc","name":"Central Bar (Mercat Central)","m":1,"act":"d5b1","q":"Central Bar Ricard Camarena, Mercat Central, València","blogs":[12]},
    {"id":"cityofarts","group":"vlc","name":"City of Arts and Sciences","m":1,"act":"d6b1","q":"City of Arts and Sciences, València","yt":"https://youtube.com/watch?v=bXX-0J9V5vU&t=309","blogs":[11]},
    {"id":"hemisferic","group":"vlc","name":"Hemisfèric","m":1,"act":"d6b1","q":"Hemisfèric, València","yt":"https://youtube.com/watch?v=dsaL__wExAQ&t=510","blogs":[12]},
    {"id":"hundred","group":"vlc","name":"Hundred Burgers","m":1,"q":"Hundred, València","yt":"https://youtube.com/watch?v=aiohx6ug6vs&t=420"},
    {"id":"viveros","group":"vlc","name":"Jardins del Real","m":1,"q":"Jardins del Real, València","yt":"https://youtube.com/watch?v=l8llwIy4Jqg&t=253"},
    {"id":"estrecha","group":"vlc","name":"La Estrecha","m":1,"q":"La Estrecha, València","yt":"https://youtube.com/watch?v=GAa385fWXF8&t=300"},
    {"id":"lonja","group":"vlc","name":"La Lonja de la Seda","m":1,"act":"d5b2","q":"La Lonja de la Seda, València","yt":"https://youtube.com/watch?v=WlimrdOuQ5M&t=283","blogs":[12]},
    {"id":"lapepica","group":"vlc","name":"La Pepica","m":1,"q":"La Pepica, Passeig de Neptú, València","blogs":[14]},
    {"id":"colon","group":"vlc","name":"Mercat de Colón","m":1,"q":"Mercat de Colón, València","yt":"https://youtube.com/watch?v=dsaL__wExAQ&t=750"},
    {"id":"bellesarts","group":"vlc","name":"Museu de Belles Arts de València","m":1,"q":"Museu de Belles Arts de València, València","yt":"https://youtube.com/watch?v=V792VL2-Qas&t=352"},
    {"id":"ceramics","group":"vlc","name":"Museu Nacional de Ceràmica","m":1,"q":"Museu Nacional de Ceràmica, València","blogs":[12]},
    {"id":"oceanografic","group":"vlc","name":"Oceanogràfic","m":1,"act":"d6b2","q":"Oceanogràfic, València","yt":"https://youtube.com/watch?v=aiohx6ug6vs&t=750","blogs":[12]},
    {"id":"gulliver","group":"vlc","name":"Parque Gulliver","m":1,"act":"d4b6","q":"Parque Gulliver, València"},
    {"id":"ajuntament","group":"vlc","name":"Plaça de l’Ajuntament","m":1,"q":"Plaça de l’Ajuntament, València","yt":"https://youtube.com/watch?v=GAa385fWXF8&t=30"},
    {"id":"reina","group":"vlc","name":"Plaça de la Reina","m":1,"q":"Plaça de la Reina, València","yt":"https://youtube.com/watch?v=GAa385fWXF8&t=120","blogs":[12]},
    {"id":"redonda","group":"vlc","name":"Plaça Redona","m":1,"q":"Plaça Redona, València","yt":"https://youtube.com/watch?v=WlimrdOuQ5M&t=595"},
    {"id":"tascaangel","group":"vlc","name":"Tasca Ángel","m":1,"q":"Tasca Ángel, València"},
    {"id":"quart","group":"vlc","name":"Torres de Quart","m":1,"q":"Torres de Quart, València","yt":"https://youtube.com/watch?v=aiohx6ug6vs&t=720","blogs":[12]},
    {"id":"umbracle","group":"vlc","name":"Umbracle","m":1,"act":"d6b1","q":"Umbracle, València","yt":"https://youtube.com/watch?v=dsaL__wExAQ&t=540","blogs":[11]},
    {"id":"cafehoras","group":"vlc","name":"Café de las Horas","m":0,"q":"Café de las Horas, València","blogs":[11]},
    {"id":"casaroberto","group":"vlc","name":"Casa Roberto","m":0,"q":"Casa Roberto, València","blogs":[14]},
    {"id":"valor","group":"vlc","name":"Chocolatería Valor","m":0,"q":"Chocolatería Valor, Plaza de la Reina, València","blogs":[12]},
    {"id":"elsaler","group":"vlc","name":"El Saler & Devesa beaches","m":0,"q":"Platja del Saler, València","blogs":[13]},
    {"id":"ivam","group":"vlc","name":"IVAM","m":0,"q":"IVAM Institut Valencià d’Art Modern, València","blogs":[11]},
    {"id":"lariua","group":"vlc","name":"La Riuà","m":0,"q":"La Riuà, València","blogs":[11]},
    {"id":"mercatrussafa","group":"vlc","name":"Mercat de Russafa","m":0,"q":"Mercat de Russafa, València","blogs":[12]},
    {"id":"fallasmuseum","group":"vlc","name":"Museu Faller","m":0,"q":"Museu Faller, València","blogs":[12]},
    {"id":"levante","group":"vlc","name":"Restaurante Levante","m":0,"q":"Restaurante Levante, València","blogs":[14]},
    {"id":"lienzo","group":"vlc","name":"Restaurante Lienzo","m":0,"q":"Restaurante Lienzo, València","blogs":[11]},
    {"id":"albufera","group":"aroundvlc","name":"Albufera Natural Park","m":1,"act":"d6b4","q":"Albufera Natural Park, València","yt":"https://youtube.com/watch?v=LkpItPttOyM&t=1422","blogs":[17,18]},
    {"id":"cullera","group":"aroundvlc","name":"Cullera","m":1,"q":"Cullera, València"},
    {"id":"elpalmar","group":"aroundvlc","name":"El Palmar","m":1,"act":"d6b3","q":"el Palmar, València","yt":"https://youtube.com/watch?v=dsaL__wExAQ&t=660","blogs":[11,18]},
    {"id":"golapujol","group":"aroundvlc","name":"Mirador de la Gola de Pujol","m":1,"act":"d6b5","q":"Mirador de la Gola de Pujol, València","yt":"https://youtube.com/watch?v=dsaL__wExAQ&t=660","blogs":[18]},
    {"id":"montanejos","group":"aroundvlc","name":"Montanejos","m":1,"q":"Montanejos, València","yt":"https://youtube.com/watch?v=V792VL2-Qas&t=610","blogs":[16,18]},
    {"id":"portsaplaya","group":"aroundvlc","name":"Port Saplaya","m":1,"q":"Port Saplaya, València","yt":"https://youtube.com/watch?v=l8llwIy4Jqg&t=485","blogs":[15,18]},
    {"id":"albarracin","group":"aroundvlc","name":"Albarracín","m":0,"q":"Albarracín, Teruel","blogs":[18]},
    {"id":"alboraya","group":"aroundvlc","name":"Alboraya & Horchatería Vida","m":0,"q":"Horchatería Vida, Alboraya","blogs":[18]},
    {"id":"morella","group":"aroundvlc","name":"Morella","m":0,"q":"Morella, Castellón","blogs":[18]},
    {"id":"peniscola","group":"aroundvlc","name":"Peñíscola","m":0,"q":"Peñíscola old town","blogs":[11,18]},
    {"id":"sagunto","group":"aroundvlc","name":"Sagunto","m":0,"q":"Sagunto castle","blogs":[18,19]},
    {"id":"xativa","group":"aroundvlc","name":"Xàtiva","m":0,"q":"Xàtiva castle","blogs":[11,19]},
    {"id":"retiro","group":"mad","name":"Parque del Retiro","m":3,"q":"Parque del Retiro, Madrid","yt":"https://youtube.com/watch?v=Gu7JDzo43Zs&t=800"},
    {"id":"sanmiguel","group":"mad","name":"Mercado de San Miguel","m":1,"q":"Mercado de San Miguel, Madrid","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=420"},
    {"id":"prado","group":"mad","name":"Museo del Prado","m":1,"q":"Museo del Prado, Madrid","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=330"},
    {"id":"cristal","group":"mad","name":"Palacio de Cristal","m":1,"q":"Palacio de Cristal, Madrid","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=390"},
    {"id":"palacioreal","group":"mad","name":"Palacio Real de Madrid","m":1,"q":"Palacio Real de Madrid, Madrid","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=330"},
    {"id":"callao","group":"mad","name":"Plaza de Callao","m":1,"q":"Plaza de Callao, Madrid","yt":"https://youtube.com/watch?v=Gu7JDzo43Zs&t=33"},
    {"id":"plazamayor","group":"mad","name":"Plaza Mayor","m":1,"q":"Plaza Mayor, Madrid"},
    {"id":"puertadelsol","group":"mad","name":"Puerta del Sol","m":1,"q":"Puerta del Sol, Madrid","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=420"},
    {"id":"debod","group":"mad","name":"Templo de Debod","m":1,"q":"Templo de Debod, Madrid","yt":"https://youtube.com/watch?v=13Y7H5DNyC4&t=450"},
    {"id":"setas","group":"sev","name":"Setas de Sevilla","m":5,"q":"Setas de Sevilla, Sevilla","yt":"https://youtube.com/watch?v=--Ovm-KBvuw&t=1012"},
    {"id":"santacruz","group":"sev","name":"Barrio Santa Cruz","m":4,"q":"Barrio Santa cruz, Sevilla","yt":"https://youtube.com/watch?v=kcalkfcK6ZA&t=308"},
    {"id":"sevcathedral","group":"sev","name":"Catedral de Sevilla","m":4,"q":"Catedral de Sevilla, Sevilla","yt":"https://youtube.com/watch?v=MqNUJltF6ns&t=700"},
    {"id":"sevespana","group":"sev","name":"Plaza de España","m":4,"q":"Plaza de España, Sevilla","yt":"https://youtube.com/watch?v=--Ovm-KBvuw&t=723"},
    {"id":"pilatos","group":"sev","name":"Casa de Pilatos","m":3,"q":"Casa de Pilatos, Sevilla","yt":"https://youtube.com/watch?v=MqNUJltF6ns&t=825"},
    {"id":"archivo","group":"sev","name":"Archivo de Indias","m":2,"q":"Archivo de Indias, Sevilla","yt":"https://youtube.com/watch?v=--Ovm-KBvuw&t=1468"},
    {"id":"duenas","group":"sev","name":"Palacio de las Dueñas","m":2,"q":"Palacio de las Dueñas, Sevilla","yt":"https://youtube.com/watch?v=--Ovm-KBvuw&t=1124"},
    {"id":"marialuisa","group":"sev","name":"Parque de María Luisa","m":2,"q":"Parque de María Luisa, Sevilla","yt":"https://youtube.com/watch?v=MqNUJltF6ns&t=123"},
    {"id":"alcazar","group":"sev","name":"Real Alcázar de Sevilla","m":2,"q":"Real Alcázar de Sevilla, Sevilla","yt":"https://youtube.com/watch?v=MqNUJltF6ns&t=195"},
    {"id":"alameda","group":"sev","name":"Alameda de Hércules","m":1,"q":"Alameda de Hércules, Sevilla","yt":"https://youtube.com/watch?v=MqNUJltF6ns&t=657"},
    {"id":"salvador","group":"sev","name":"Iglesia del Salvador","m":1,"q":"Iglesia del Salvador, Sevilla","yt":"https://youtube.com/watch?v=MqNUJltF6ns&t=805"},
    {"id":"italica","group":"sev","name":"Itálica","m":1,"q":"Italica, Sevilla","yt":"https://youtube.com/watch?v=MqNUJltF6ns&t=924"},
    {"id":"torredeloro","group":"sev","name":"Torre del Oro","m":1,"q":"Torre del Oro, Sevilla","yt":"https://youtube.com/watch?v=kcalkfcK6ZA&t=271"},
    {"id":"triana","group":"sev","name":"Triana","m":1,"q":"Triana, Sevilla","yt":"https://youtube.com/watch?v=--Ovm-KBvuw&t=80"},
  ],
  tips: [
    {"id":"tk1","cat":"tickets","src":["v",3]},
    {"id":"tk2","cat":"tickets","src":["v",3]},
    {"id":"tk3","cat":"tickets","src":["v"]},
    {"id":"tk4","cat":"tickets","src":["v",2]},
    {"id":"tk5","cat":"tickets","src":["v"]},
    {"id":"tk6","cat":"tickets","src":[1]},
    {"id":"tk7","cat":"tickets","src":["v"]},
    {"id":"tk8","cat":"tickets","src":["v",0]},
    {"id":"tk9","cat":"tickets","src":["v"]},
    {"id":"tk10","cat":"tickets","src":["v",13]},
    {"id":"tk11","cat":"tickets","src":["v"]},
    {"id":"tk12","cat":"tickets","src":["v"]},
    {"id":"tk13","cat":"tickets","src":["v",11]},
    {"id":"tk14","cat":"tickets","src":[11]},
    {"id":"tk15","cat":"tickets","src":[11]},
    {"id":"tk16","cat":"tickets","src":[10]},
    {"id":"tk17","cat":"tickets","src":[9]},
    {"id":"tk18","cat":"tickets","src":[8]},
    {"id":"tk19","cat":"tickets","src":[15]},
    {"id":"tr1","cat":"transport","src":["v",3]},
    {"id":"tr2","cat":"transport","src":["v",0]},
    {"id":"tr3","cat":"transport","src":["v"]},
    {"id":"tr4","cat":"transport","src":["v"]},
    {"id":"tr5","cat":"transport","src":["v"]},
    {"id":"tr6","cat":"transport","src":["v",1]},
    {"id":"tr7","cat":"transport","src":[0]},
    {"id":"tr8","cat":"transport","src":["v"]},
    {"id":"tr9","cat":"transport","src":[2]},
    {"id":"tr10","cat":"transport","src":["v",9,10]},
    {"id":"tr11","cat":"transport","src":[9]},
    {"id":"tr12","cat":"transport","src":[10]},
    {"id":"tr13","cat":"transport","src":[9]},
    {"id":"tr14","cat":"transport","src":["v",13]},
    {"id":"tr15","cat":"transport","src":["v",11]},
    {"id":"tr16","cat":"transport","src":["v"]},
    {"id":"tr17","cat":"transport","src":[11]},
    {"id":"tr18","cat":"transport","src":["v",15]},
    {"id":"tr19","cat":"transport","src":["v",17,18]},
    {"id":"tr20","cat":"transport","src":[18]},
    {"id":"tr21","cat":"transport","src":["v"]},
    {"id":"fd1","cat":"food","src":["v",11,14]},
    {"id":"fd2","cat":"food","src":["v",11]},
    {"id":"fd3","cat":"food","src":[14]},
    {"id":"fd4","cat":"food","src":["v",17,18]},
    {"id":"fd5","cat":"food","src":["v",2,13]},
    {"id":"fd6","cat":"food","src":["v",3,4]},
    {"id":"fd7","cat":"food","src":["v",12]},
    {"id":"fd8","cat":"food","src":["v",12]},
    {"id":"fd9","cat":"food","src":["v",11]},
    {"id":"fd10","cat":"food","src":["v",3]},
    {"id":"fd11","cat":"food","src":[3]},
    {"id":"fd12","cat":"food","src":["v",1,3]},
    {"id":"fd13","cat":"food","src":["v"]},
    {"id":"fd14","cat":"food","src":[4]},
    {"id":"fd15","cat":"food","src":[6]},
    {"id":"fd16","cat":"food","src":[2]},
    {"id":"fd17","cat":"food","src":["v"]},
    {"id":"fd18","cat":"food","src":["v",4]},
    {"id":"fd19","cat":"food","src":["v"]},
    {"id":"fd20","cat":"food","src":["v"]},
    {"id":"fd21","cat":"food","src":[15]},
    {"id":"fd22","cat":"food","src":[8]},
    {"id":"tm1","cat":"timing","src":["v",20]},
    {"id":"tm2","cat":"timing","src":["v",5,16]},
    {"id":"tm3","cat":"timing","src":["v",11]},
    {"id":"tm4","cat":"timing","src":["v",13]},
    {"id":"tm5","cat":"timing","src":[21]},
    {"id":"tm6","cat":"timing","src":[5,21]},
    {"id":"tm7","cat":"timing","src":[20]},
    {"id":"tm8","cat":"timing","src":[3]},
    {"id":"tm9","cat":"timing","src":["v",0]},
    {"id":"tm10","cat":"timing","src":["v"]},
    {"id":"tm11","cat":"timing","src":[5]},
    {"id":"tm12","cat":"timing","src":[5]},
    {"id":"tm13","cat":"timing","src":[8]},
    {"id":"tm14","cat":"timing","src":["v",18]},
    {"id":"sf1","cat":"safety","src":["v",2,6]},
    {"id":"sf2","cat":"safety","src":["v"]},
    {"id":"sf3","cat":"safety","src":["v",2]},
    {"id":"sf4","cat":"safety","src":["v",15]},
    {"id":"sf5","cat":"safety","src":[2]},
    {"id":"sf6","cat":"safety","src":[8]},
    {"id":"bd1","cat":"budget","src":["v"]},
    {"id":"bd2","cat":"budget","src":["v"]},
    {"id":"bd3","cat":"budget","src":["v"]},
    {"id":"bd4","cat":"budget","src":["v",13]},
    {"id":"bd5","cat":"budget","src":["v"]},
    {"id":"bd6","cat":"budget","src":["v"]},
    {"id":"bd7","cat":"budget","src":["v",15]},
    {"id":"bd8","cat":"budget","src":[9]},
    {"id":"bd9","cat":"budget","src":[8]},
    {"id":"st1","cat":"stay","src":["v",0]},
    {"id":"st2","cat":"stay","src":[0]},
    {"id":"st3","cat":"stay","src":[6]},
    {"id":"st4","cat":"stay","src":[2]},
    {"id":"st5","cat":"stay","src":["v",13,15]},
    {"id":"st6","cat":"stay","src":[3,16,20]},
    {"id":"st7","cat":"stay","src":["v"]},
    {"id":"dt1","cat":"daytrip","src":["v",8]},
    {"id":"dt2","cat":"daytrip","src":[6]},
    {"id":"dt3","cat":"daytrip","src":["v",7]},
    {"id":"dt4","cat":"daytrip","src":[7]},
    {"id":"dt5","cat":"daytrip","src":["v",1,7]},
    {"id":"dt6","cat":"daytrip","src":[7]},
    {"id":"dt7","cat":"daytrip","src":[7]},
    {"id":"dt9","cat":"daytrip","src":["v"]},
    {"id":"dt10","cat":"daytrip","src":["v",17,18]},
    {"id":"dt11","cat":"daytrip","src":[17]},
    {"id":"dt12","cat":"daytrip","src":["v",18]},
    {"id":"dt13","cat":"daytrip","src":["v"]},
    {"id":"dt14","cat":"daytrip","src":["v",16,18]},
    {"id":"dt15","cat":"daytrip","src":[18,19]},
    {"id":"dt16","cat":"daytrip","src":[11,19]},
    {"id":"dt17","cat":"daytrip","src":[11,18]},
    {"id":"dt19","cat":"daytrip","src":[18]},
    {"id":"dt20","cat":"daytrip","src":[18]},
    {"id":"dt21","cat":"daytrip","src":[16]},
    {"id":"dt22","cat":"daytrip","src":["v"]},
    {"id":"et1","cat":"etiquette","src":[3]},
    {"id":"et2","cat":"etiquette","src":[2]},
    {"id":"et3","cat":"etiquette","src":[3]},
    {"id":"et4","cat":"etiquette","src":[3]},
    {"id":"et5","cat":"etiquette","src":[6]},
    {"id":"et6","cat":"etiquette","src":[13]},
    {"id":"et7","cat":"etiquette","src":[15]},
    {"id":"et8","cat":"etiquette","src":["v"]},
    {"id":"ms1","cat":"misc","src":["v",15]},
    {"id":"ms2","cat":"misc","src":[3]},
    {"id":"ms3","cat":"misc","src":[2,16]},
    {"id":"ms4","cat":"misc","src":["v"]},
    {"id":"ms5","cat":"misc","src":["v"]},
  ],
  videos: [
    {"id":"uK_ghSTfn6U","title":"3 Days in Barcelona, Spain! BEST Things To Do, Eat, + See (Travel Guide)"},
    {"id":"YILzH4iI76E","title":"How to Spend 5 Days in BARCELONA Spain | Travel Itinerary"},
    {"id":"9tyzP8YDjDw","title":"The PERFECT 3 Days in Barcelona! Best Things to Do & Eat (Travel Guide)"},
    {"id":"juHOYfdXNQA","title":"How to Spend 4 Days in BARCELONA Spain | Travel Itinerary & Travel Guide"},
    {"id":"Gu7JDzo43Zs","title":"The PERFECT Trip to Madrid Spain! Best Things to Do & Eat (Travel Guide)"},
    {"id":"9CN46dCSwE8","title":"WATCH THIS before your trip to MADRID 🇪🇸 Madrid Travel Guide 2025"},
    {"id":"5q-reJJS0C8","title":"Madrid Travel Guide 2026: Tips from a Local (Madrileña)"},
    {"id":"dJajNiR_YbQ","title":"The PERFECT 3 Days in Madrid! Best Things to Do & Eat (Travel Guide)"},
    {"id":"--Ovm-KBvuw","title":"A PERFECT Trip to SEVILLE, SPAIN (We Fell in LOVE!) 🇪🇸 Things to Do + Eat!"},
    {"id":"MqNUJltF6ns","title":"Seville, Spain Itinerary | The Best Things To Do In 3 Days"},
    {"id":"kcalkfcK6ZA","title":"How to Spend 4 Days in SEVILLE Spain | The Perfect Travel Guide"},
    {"id":"mpVgXBNrIFg","title":"Seville Travel Guide 🇪🇸 | The Most Beautiful City in Europe!? (Seville, Spain)"},
    {"id":"13Y7H5DNyC4","title":"BARCELONA, MADRID & VALENCIA in 8 Days: Complete Spain Travel Guide with Costs, Things to Do & See"},
    {"id":"7ohQXNocEqQ","title":"Vlog #355 - Spain. Road from Barcelona to Valencia ."},
    {"id":"aiohx6ug6vs","title":"The Ultimate Guide to Valencia"},
    {"id":"bXX-0J9V5vU","title":"Valencia Travel Guide 🇪🇸 Things to Do in Valencia Spain"},
    {"id":"cKWUZLXbJKk","title":"How to Spend 3 Days in BARCELONA Spain | Travel Itinerary"},
    {"id":"dsaL__wExAQ","title":"How to Spend 3 Days in VALENCIA Spain | The Perfect Travel Itinerary"},
    {"id":"GAa385fWXF8","title":"How to Spend 2 Days in VALENCIA Spain | Travel Itinerary"},
    {"id":"l8llwIy4Jqg","title":"👑 Valencia to Barcelona - Visit SPAIN 👑 | Travel Vlog"},
    {"id":"LkpItPttOyM","title":"I Showed My Valencia Hometown To Tourists - THIS WHAT YOU MUST SEE!"},
    {"id":"MpWGYloOB3s","title":"Barcelona to Valencia by road - [4K]"},
    {"id":"NRu-HV5gWYE","title":"BARCELONA to VALENCIA by TRAIN - quick day trip"},
    {"id":"o6VsyWyVxBY","title":"THINGS TO KNOW BEFORE YOU GO TO VALENCIA"},
    {"id":"SCVlA4XUrU0","title":"BARCELONA Road TRIP | VALENCIA SPAIN travel VLOG | is MADRID safe?"},
    {"id":"sRTZVjgUwHg","title":"TRAVEL WITH ME TO SPAIN 🇪🇸 barcelona on a budge, 1st time exploring valencia, tapas + sangria!"},
    {"id":"Tp1Qr0WPEnw","title":"5 HOURS SPAIN ROAD TRIP | FROM DENIA TO VALENCIA,BARCELONA,MADRID"},
    {"id":"V792VL2-Qas","title":"VALENCIA, SPAIN | 10 Incredible Things To Do In & Around Valencia"},
    {"id":"WlimrdOuQ5M","title":"Is This Spain's BEST City!? 🇪🇸 Valencia Travel Guide (Best Things To Do)"},
  ],
  blogs: [
    {"name":"Go Ask A Local","url":"https://goaskalocal.com/blog/3-day-barcelona-itinerary"},
    {"name":"Nomadic Matt","url":"https://www.nomadicmatt.com/travel-blogs/barcelona-itinerary/"},
    {"name":"Happy to Wander","url":"https://happytowander.com/barcelona-travel-tips/"},
    {"name":"In Between Pictures","url":"https://inbetweenpictures.com/blog/15-barcelona-mistakes-first-time-visitors-make-according-to-a-local"},
    {"name":"Devour Tours","url":"https://devourtours.com/blog/where-to-eat-in-barcelona/"},
    {"name":"Barcelona Hacks","url":"https://barcelonahacks.com/barcelona-in-august/"},
    {"name":"Walk My World","url":"https://www.walkmyworld.com/posts/mistakes-barcelona"},
    {"name":"Barcelona Life","url":"https://www.barcelona-life.com/barcelona/day-trips"},
    {"name":"Probe Around The Globe","url":"https://www.probearoundtheglobe.com/barcelona-to-montserrat-by-train/"},
    {"name":"ShowMeTheJourney","url":"https://showmethejourney.com/train-travel-info/journeys/from-barcelona-to-valencia-by-train/"},
    {"name":"The Man in Seat 61","url":"https://www.seat61.com/train-travel-in-spain.htm"},
    {"name":"Pack The Suitcases","url":"https://www.packthesuitcases.com/3-days-in-valencia-itinerary-spain/"},
    {"name":"Driftwood Journals","url":"https://www.driftwoodjournals.com/3-day-valencia-itinerary-for-first-time-visitors-oranges-palm-trees-paella/"},
    {"name":"Along Dusty Roads","url":"https://www.alongdustyroads.com/posts/2017/1/13/things-to-know-visiting-valencia-spain"},
    {"name":"Devour Tours (paella guide)","url":"https://devourtours.com/blog/best-places-for-paella-in-valencia/"},
    {"name":"My Path in the World","url":"https://mypathintheworld.com/valencia-travel-tips/"},
    {"name":"Abroad in Valencia","url":"https://abroadinvalencia.com/valencia-in-august/"},
    {"name":"bye:myself","url":"https://byemyself.com/day-trip-to-the-albufera-nature-reserve-outside-valencia/"},
    {"name":"The Unconventional Route","url":"https://www.theunconventionalroute.com/valencia-day-trips/"},
    {"name":"An Adventurous World","url":"https://www.anadventurousworld.com/day-trips-from-valencia/"},
    {"name":"Pretty Wild World","url":"https://www.prettywildworld.com/spain-in-august/"},
    {"name":"How2Spanish","url":"https://how2spanish.com/en/blog/why-spain-closes-in-august"},
  ]
};
