/* One photograph per itinerary stop — generated, do not hand-edit.
 *
 * Wikimedia Commons pictures carrying the author and licence they were
 * published under, resolved from tools/photo-queries.json. app.js hangs
 * them off the stop cards and shows the credit in the viewer, which is
 * the condition on using them at all.
 *
 * Regenerate:  node tools/photos.mjs
 */
window.PHOTOS = {
  "spain": {
    "d1b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/6/6d/Barcelona_-_Carrer_del_Bisbe.jpg","w":794,"h":1094,"by":"Llull","lic":"CC BY-SA 2.0","licUrl":"https://creativecommons.org/licenses/by-sa/2.0","page":"https://commons.wikimedia.org/wiki/File:Barcelona_-_Carrer_del_Bisbe.jpg"},
    "d2b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/SF_maig_2_cropped.jpg/960px-SF_maig_2_cropped.jpg","w":900,"h":1310,"by":"Canaan","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:SF_maig_2_cropped.jpg"},
    "d2b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Casa_Mil%C3%A0%2C_general_view.jpg/960px-Casa_Mil%C3%A0%2C_general_view.jpg","w":900,"h":701,"by":"Thomas Ledl","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Casa_Mil%C3%A0,_general_view.jpg"},
    "d2b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Parc_guell_-_panoramio.jpg/960px-Parc_guell_-_panoramio.jpg","w":900,"h":675,"by":"essetefano","lic":"CC BY 3.0","licUrl":"https://creativecommons.org/licenses/by/3.0","page":"https://commons.wikimedia.org/wiki/File:Parc_guell_-_panoramio.jpg"},
    "d2b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Casa_Batllo_Overview_Barcelona_Spain_cut.jpg/960px-Casa_Batllo_Overview_Barcelona_Spain_cut.jpg","w":900,"h":1109,"by":"ChristianSchd","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Casa_Batllo_Overview_Barcelona_Spain_cut.jpg"},
    "d3b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Abbey_of_Montserrat_02.jpg/960px-Abbey_of_Montserrat_02.jpg","w":900,"h":621,"by":"Bernard Gagnon","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Abbey_of_Montserrat_02.jpg"},
    "d3b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Barcelona_%2816877599244%29.jpg/960px-Barcelona_%2816877599244%29.jpg","w":900,"h":599,"by":"Kuba Bożanowski from Warsaw, Poland","lic":"CC BY 2.0","licUrl":"https://creativecommons.org/licenses/by/2.0","page":"https://commons.wikimedia.org/wiki/File:Barcelona_(16877599244).jpg"},
    "d4b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Fa%C3%A7ana_Santa_Caterina.jpg/960px-Fa%C3%A7ana_Santa_Caterina.jpg","w":900,"h":600,"by":"Albert Prat","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Fa%C3%A7ana_Santa_Caterina.jpg"},
    "d4b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Santa_Maria_del_Mar%2C_Barcelona_05.jpg/960px-Santa_Maria_del_Mar%2C_Barcelona_05.jpg","w":900,"h":1037,"by":"Kent Wang","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Santa_Maria_del_Mar,_Barcelona_05.jpg"},
    "d4b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/4/48/Museu_Picasso_Barcelona.jpg","w":369,"h":500,"by":"uayebt","lic":"CC BY 2.0","licUrl":"https://creativecommons.org/licenses/by/2.0","page":"https://commons.wikimedia.org/wiki/File:Museu_Picasso_Barcelona.jpg"},
    "d4b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/La_Rambla_de_Barcelona_%28May_2022%29.jpg/960px-La_Rambla_de_Barcelona_%28May_2022%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":1200,"by":"Ramonscat","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:La_Rambla_de_Barcelona_(May_2022).jpg"},
    "d4b6": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Parque_Gulliver_2007_-_puroticorico.jpg/960px-Parque_Gulliver_2007_-_puroticorico.jpg","w":900,"h":675,"by":"https://www.flickr.com/photos/puroticorico/","lic":"CC BY 2.0","licUrl":"https://creativecommons.org/licenses/by/2.0","page":"https://commons.wikimedia.org/wiki/File:Parque_Gulliver_2007_-_puroticorico.jpg"},
    "d4b7": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Mercat_de_Russafa.JPG/960px-Mercat_de_Russafa.JPG","w":900,"h":675,"by":"Joanbanjo","lic":"Public domain","licUrl":null,"page":"https://commons.wikimedia.org/wiki/File:Mercat_de_Russafa.JPG"},
    "d5b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Interior_mercado_central_Valencia_06.JPG/960px-Interior_mercado_central_Valencia_06.JPG","w":900,"h":600,"by":"Miguel Hermoso Cuesta","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Interior_mercado_central_Valencia_06.JPG"},
    "d5b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Valencia%2C_loggia_della_seta%2C_interno%2C_sala_delle_contrattazioni%2C_01%2C0.jpg/960px-Valencia%2C_loggia_della_seta%2C_interno%2C_sala_delle_contrattazioni%2C_01%2C0.jpg","w":900,"h":964,"by":"Francesco Bini","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Valencia,_loggia_della_seta,_interno,_sala_delle_contrattazioni,_01,0.jpg"},
    "d5b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Valencia_cathedral_2022_-_north_fa%C3%A7ade_dawn.jpg/960px-Valencia_cathedral_2022_-_north_fa%C3%A7ade_dawn.jpg","w":900,"h":600,"by":"Fernando Pascullo","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Valencia_cathedral_2022_-_north_fa%C3%A7ade_dawn.jpg"},
    "d5b5": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Playa_de_la_Malvarrosa_%28Valencia%29_01.jpg/960px-Playa_de_la_Malvarrosa_%28Valencia%29_01.jpg","w":900,"h":675,"by":"Manuel Martín Vicente from Spain","lic":"CC BY 2.0","licUrl":"https://creativecommons.org/licenses/by/2.0","page":"https://commons.wikimedia.org/wiki/File:Playa_de_la_Malvarrosa_(Valencia)_01.jpg"},
    "d5b6": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Puerta_de_los_Serranos%2C_Valencia%2C_Espa%C3%B1a%2C_2014-06-30%2C_DD_86.JPG/960px-Puerta_de_los_Serranos%2C_Valencia%2C_Espa%C3%B1a%2C_2014-06-30%2C_DD_86.JPG","w":900,"h":620,"by":"Diego Delso","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Puerta_de_los_Serranos,_Valencia,_Espa%C3%B1a,_2014-06-30,_DD_86.JPG"},
    "d5b7": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Valencia-_Barrio_del_Carmen_%2825095338261%29.jpg/960px-Valencia-_Barrio_del_Carmen_%2825095338261%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":600,"by":"Jorge Franganillo from Barcelona, Spain","lic":"CC BY 2.0","licUrl":"https://creativecommons.org/licenses/by/2.0","page":"https://commons.wikimedia.org/wiki/File:Valencia-_Barrio_del_Carmen_(25095338261).jpg"},
    "d6b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Valencia%2C_Ciudad_de_las_Ciencias_y_de_las_Artes.jpg/960px-Valencia%2C_Ciudad_de_las_Ciencias_y_de_las_Artes.jpg","w":900,"h":598,"by":"Jcca76","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Valencia,_Ciudad_de_las_Ciencias_y_de_las_Artes.jpg"},
    "d6b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/2002_wurde_das_Ozeaneum_in_Valencia_er%C3%B6ffnet._14.jpg/960px-2002_wurde_das_Ozeaneum_in_Valencia_er%C3%B6ffnet._14.jpg","w":900,"h":1008,"by":"Holger Uwe Schmitt","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:2002_wurde_das_Ozeaneum_in_Valencia_er%C3%B6ffnet._14.jpg"},
    "d6b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Barca_en_la_Albufera_de_Valencia_01.jpg/960px-Barca_en_la_Albufera_de_Valencia_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":600,"by":"Dorieo","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Barca_en_la_Albufera_de_Valencia_01.jpg"},
    "d7b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Jard%C3%AD_del_T%C3%BAria_de_Val%C3%A8ncia%2C_riuet.JPG/960px-Jard%C3%AD_del_T%C3%BAria_de_Val%C3%A8ncia%2C_riuet.JPG","w":900,"h":624,"by":"Joanbanjo","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Jard%C3%AD_del_T%C3%BAria_de_Val%C3%A8ncia,_riuet.JPG"}
  },
  "italy": {
    "i1s1": {"src":"https://upload.wikimedia.org/wikipedia/commons/0/04/Trapani_from_erice.jpg","w":800,"h":625,"by":"ChrisO","lic":"CC BY-SA 3.0","licUrl":"http://creativecommons.org/licenses/by-sa/3.0/","page":"https://commons.wikimedia.org/wiki/File:Trapani_from_erice.jpg"},
    "i2b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Island_Horizon_%2869299375%29.jpeg/960px-Island_Horizon_%2869299375%29.jpeg","w":900,"h":600,"by":"Luca Canepa","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Island_Horizon_(69299375).jpeg"},
    "i2b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/c/cd/Erice_-_Stefano_Pannucci.jpg","w":960,"h":640,"by":"Pannucci Stefano","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Erice_-_Stefano_Pannucci.jpg"},
    "i3b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Normandiarren_gaztelua.jpg/960px-Normandiarren_gaztelua.jpg","w":900,"h":675,"by":"Lasterketak","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Normandiarren_gaztelua.jpg"},
    "i3b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ballar%C3%B2%2C_gente_en_el_mercado%2C_Palermo%2C_Sicilia%2C_Italia%2C_2015.JPG/960px-Ballar%C3%B2%2C_gente_en_el_mercado%2C_Palermo%2C_Sicilia%2C_Italia%2C_2015.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":675,"by":"Benjamín Núñez González","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Ballar%C3%B2,_gente_en_el_mercado,_Palermo,_Sicilia,_Italia,_2015.JPG"},
    "i3b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Santa_Caterina_%28Palermo%29.JPG/960px-Santa_Caterina_%28Palermo%29.JPG","w":900,"h":1200,"by":"Giuseppe ME","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Santa_Caterina_(Palermo).JPG"},
    "i3b5": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Foro_Italico_10.jpg/960px-Foro_Italico_10.jpg","w":900,"h":675,"by":"Dedda71","lic":"CC BY 3.0","licUrl":"https://creativecommons.org/licenses/by/3.0","page":"https://commons.wikimedia.org/wiki/File:Foro_Italico_10.jpg"},
    "i4b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Il_golfo_di_Mondello.jpg/960px-Il_golfo_di_Mondello.jpg","w":900,"h":572,"by":"Andrea Calcagno from PALERMO, Italia","lic":"CC BY-SA 2.0","licUrl":"https://creativecommons.org/licenses/by-sa/2.0","page":"https://commons.wikimedia.org/wiki/File:Il_golfo_di_Mondello.jpg"},
    "i4b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/f/f5/Capo_Gallo_Faro.JPG","w":640,"h":461,"by":"Alberto Romeo albertoromeo@neomedia.it http://www.romeofotosub.it","lic":"CC BY 3.0","licUrl":"https://creativecommons.org/licenses/by/3.0","page":"https://commons.wikimedia.org/wiki/File:Capo_Gallo_Faro.JPG"},
    "i5b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Giardini_Naxos_panorama_23-01-2023_cropped_2.jpg/960px-Giardini_Naxos_panorama_23-01-2023_cropped_2.jpg","w":900,"h":832,"by":"Jeanne Griffin","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Giardini_Naxos_panorama_23-01-2023_cropped_2.jpg"},
    "i5b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Aerial_image_of_the_coast_of_Taormina_%28view_from_the_southeast%29.jpg/960px-Aerial_image_of_the_coast_of_Taormina_%28view_from_the_southeast%29.jpg","w":900,"h":600,"by":"Carsten Steger","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Aerial_image_of_the_coast_of_Taormina_(view_from_the_southeast).jpg"},
    "i6b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Taormina_BW_2012-10-05_16-23-05_stitch.jpg/960px-Taormina_BW_2012-10-05_16-23-05_stitch.jpg","w":900,"h":387,"by":"Berthold Werner","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Taormina_BW_2012-10-05_16-23-05_stitch.jpg"},
    "i6b5": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/0990_-_Taormina_-_Villa_Comunale_-_Foto_G._DallOrto.jpg/960px-0990_-_Taormina_-_Villa_Comunale_-_Foto_G._DallOrto.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":1200,"by":"Giovanni Dall'Orto .","lic":"Attribution","licUrl":null,"page":"https://commons.wikimedia.org/wiki/File:0990_-_Taormina_-_Villa_Comunale_-_Foto_G._DallOrto.jpg"},
    "i6b6": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/IsolaBellaView.jpg/960px-IsolaBellaView.jpg","w":900,"h":526,"by":"Solomonn Levi","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:IsolaBellaView.jpg"},
    "i7b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Mt_Etna_and_Catania1.jpg/960px-Mt_Etna_and_Catania1.jpg","w":900,"h":367,"by":"BenAveling","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Mt_Etna_and_Catania1.jpg"}
  },
  "mallorca": {
    "m1b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/3/3d/South_Wigston_railway_station_in_2006.jpg","w":640,"h":427,"by":"Kate Jewell","lic":"CC BY-SA 2.0","licUrl":"https://creativecommons.org/licenses/by-sa/2.0","page":"https://commons.wikimedia.org/wiki/File:South_Wigston_railway_station_in_2006.jpg"},
    "m1b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Vistas%27arenalpalma.jpg/960px-Vistas%27arenalpalma.jpg","w":900,"h":514,"by":"Chixoy","lic":"CC BY-SA 3.0","licUrl":"http://creativecommons.org/licenses/by-sa/3.0/","page":"https://commons.wikimedia.org/wiki/File:Vistas%27arenalpalma.jpg"},
    "m2b1": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/0051-Reiterstatur_Palma.JPG/960px-0051-Reiterstatur_Palma.JPG","w":900,"h":675,"by":"Arno.Ho","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:0051-Reiterstatur_Palma.JPG"},
    "m2b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/8/83/Castillo_de_Bellver.jpg","w":612,"h":434,"by":"Poniol60","lic":"Public domain","licUrl":null,"page":"https://commons.wikimedia.org/wiki/File:Castillo_de_Bellver.jpg"},
    "m2b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Es_Baluard_01.jpg/960px-Es_Baluard_01.jpg","w":900,"h":675,"by":"Olaf Tausch","lic":"CC BY 3.0","licUrl":"https://creativecommons.org/licenses/by/3.0","page":"https://commons.wikimedia.org/wiki/File:Es_Baluard_01.jpg"},
    "m2b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Llotja_palma.jpg/960px-Llotja_palma.jpg","w":900,"h":797,"by":"Felivet","lic":"Public domain","licUrl":null,"page":"https://commons.wikimedia.org/wiki/File:Llotja_palma.jpg"},
    "m2b5": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Almudaina_catedral.jpg/960px-Almudaina_catedral.jpg","w":900,"h":600,"by":"Antoni I. Alomar Canyelles","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Almudaina_catedral.jpg"},
    "m2b6": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Palma_Banys_%C3%80rabs.jpg/960px-Palma_Banys_%C3%80rabs.jpg","w":900,"h":1359,"by":"Adrian Tync","lic":"CC BY-SA 4.0","licUrl":"https://creativecommons.org/licenses/by-sa/4.0","page":"https://commons.wikimedia.org/wiki/File:Palma_Banys_%C3%80rabs.jpg"},
    "m2b7": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Carrer_de_Soler%2C_barri_de_Santa_Catalina.JPG/960px-Carrer_de_Soler%2C_barri_de_Santa_Catalina.JPG","w":900,"h":666,"by":"Chixoy","lic":"CC BY-SA 3.0","licUrl":"http://creativecommons.org/licenses/by-sa/3.0/","page":"https://commons.wikimedia.org/wiki/File:Carrer_de_Soler,_barri_de_Santa_Catalina.JPG"},
    "m3b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Tren_de_S%C3%B3ller_05.jpg/960px-Tren_de_S%C3%B3ller_05.jpg","w":900,"h":675,"by":"Olaf Tausch","lic":"CC BY 3.0","licUrl":"https://creativecommons.org/licenses/by/3.0","page":"https://commons.wikimedia.org/wiki/File:Tren_de_S%C3%B3ller_05.jpg"},
    "m3b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Tram_from_the_Port_promenade_to_Soller_Town_-_panoramio.jpg/960px-Tram_from_the_Port_promenade_to_Soller_Town_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":663,"by":"deepeye","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Tram_from_the_Port_promenade_to_Soller_Town_-_panoramio.jpg"},
    "m3b5": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Sa_Calobra_04.jpg/960px-Sa_Calobra_04.jpg","w":900,"h":675,"by":"Olaf Tausch","lic":"CC BY-SA 3.0","licUrl":"http://creativecommons.org/licenses/by-sa/3.0/","page":"https://commons.wikimedia.org/wiki/File:Sa_Calobra_04.jpg"},
    "m3b6": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Platja_d%27en_Repic.jpg/960px-Platja_d%27en_Repic.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":675,"by":"RafelJuan","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Platja_d%27en_Repic.jpg"},
    "m3b7": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Vall_de_Soller.jpg/960px-Vall_de_Soller.jpg","w":900,"h":675,"by":"Top Cat 14","lic":"Public domain","licUrl":null,"page":"https://commons.wikimedia.org/wiki/File:Vall_de_Soller.jpg"},
    "m4b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Kathedrale_von_Palma_II.jpg/960px-Kathedrale_von_Palma_II.jpg","w":900,"h":697,"by":"Thomas Wolf , www.foto-tw.de","lic":"CC BY-SA 3.0 de","licUrl":"https://creativecommons.org/licenses/by-sa/3.0/de/deed.en","page":"https://commons.wikimedia.org/wiki/File:Kathedrale_von_Palma_II.jpg"},
    "m4b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Mercado_del_Olivar._Palma_de_Mallorca._-_panoramio.jpg/960px-Mercado_del_Olivar._Palma_de_Mallorca._-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":900,"by":"Николай Максимович","lic":"CC BY 3.0","licUrl":"https://creativecommons.org/licenses/by/3.0","page":"https://commons.wikimedia.org/wiki/File:Mercado_del_Olivar._Palma_de_Mallorca._-_panoramio.jpg"},
    "m4b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Mercat.de.Santa.Catalina.jpg/960px-Mercat.de.Santa.Catalina.jpg","w":900,"h":675,"by":"Paucabot","lic":"CC BY-SA 3.0","licUrl":"https://creativecommons.org/licenses/by-sa/3.0","page":"https://commons.wikimedia.org/wiki/File:Mercat.de.Santa.Catalina.jpg"},
    "m4b5": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/SES_ILLETES-MAJORKA%2C_AB-027.jpg/960px-SES_ILLETES-MAJORKA%2C_AB-027.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail","w":900,"h":586,"by":"Antekbojar","lic":"CC0","licUrl":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","page":"https://commons.wikimedia.org/wiki/File:SES_ILLETES-MAJORKA,_AB-027.jpg"},
    "m5b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Mallorca_Porto_Cristo_seaport_area_asv2023-04_img1.jpg/960px-Mallorca_Porto_Cristo_seaport_area_asv2023-04_img1.jpg","w":900,"h":506,"by":"A.Savin","lic":"FAL","licUrl":"http://artlibre.org/licence/lal/en","page":"https://commons.wikimedia.org/wiki/File:Mallorca_Porto_Cristo_seaport_area_asv2023-04_img1.jpg"},
    "m5b3": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Interior_de_las_Cuevas_del_Drach.jpg/960px-Interior_de_las_Cuevas_del_Drach.jpg","w":900,"h":600,"by":"no","lic":"CC BY 2.0","licUrl":"https://creativecommons.org/licenses/by/2.0","page":"https://commons.wikimedia.org/wiki/File:Interior_de_las_Cuevas_del_Drach.jpg"},
    "m6b2": {"src":"https://upload.wikimedia.org/wikipedia/commons/b/be/Cartuja1.JPG","w":719,"h":569,"by":"Juan Costa","lic":"CC BY-SA 3.0","licUrl":"http://creativecommons.org/licenses/by-sa/3.0/","page":"https://commons.wikimedia.org/wiki/File:Cartuja1.JPG"},
    "m6b4": {"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Deia_%28part_of%29_majorca_spain_arp.jpg/960px-Deia_%28part_of%29_majorca_spain_arp.jpg","w":900,"h":675,"by":"Photographed by Adrian Pingstone","lic":"Public domain","licUrl":null,"page":"https://commons.wikimedia.org/wiki/File:Deia_(part_of)_majorca_spain_arp.jpg"}
  }
};
